In [1]:
# 중복데이터 확인(개수)

import pandas as pd

df = pd.read_csv('data/messy_data.csv')
df.duplicated().sum()

np.int64(12)

In [2]:
# 중복데이터(내용)
d_index = df.duplicated(keep=False)
df[d_index].sort_values(by=['id'])

     id     name   age   salary  score department
0     1   user_1  56.0  59545.0  17.50        마케팅
109   1   user_1  56.0  59545.0  17.50        마케팅
108  11  user_11  28.0  64250.0  70.04         인사
10   11  user_11  28.0  64250.0  70.04         인사
18   19  user_19  41.0  38304.0  66.90         인사
110  19  user_19  41.0  38304.0  66.90         인사
106  23  user_23  19.0  52257.0  97.37         인사
22   23  user_23  19.0  52257.0  97.37         인사
30   31  user_31  59.0  74344.0  49.39         인사
111  31  user_31  59.0  74344.0  49.39         인사
105  40  user_40  38.0  46855.0  25.05         영업
39   40  user_40  38.0  46855.0  25.05         영업
44   45  user_45  42.0  62749.0  43.44         영업
104  45  user_45  42.0  62749.0  43.44         영업
103  46  user_46  31.0  30330.0  35.01         재무
45   46  user_46  31.0  30330.0  35.01         재무
53   54  user_54  61.0  42293.0   4.36         개발
101  54  user_54  61.0  42293.0   4.36         개발
70   71  user_71  51.0  38561.0  39.47         개발
102  71  user_71  51.0  38561.0  39.47         개발
80   81  user_81  38.0  50421.0    NaN         영업
107  81  user_81  38.0  50421.0    NaN         영업
100  84  user_84   NaN  56472.0  55.28         인사
83   84  user_84   NaN  56472.0  55.28         인사

In [3]:
# id는 중복되면 안됨
id_d = df.duplicated(subset=['id'])
df[id_d]

     id     name   age   salary  score department
100  84  user_84   NaN  56472.0  55.28         인사
101  54  user_54  61.0  42293.0   4.36         개발
102  71  user_71  51.0  38561.0  39.47         개발
103  46  user_46  31.0  30330.0  35.01         재무
104  45  user_45  42.0  62749.0  43.44         영업
105  40  user_40  38.0  46855.0  25.05         영업
106  23  user_23  19.0  52257.0  97.37         인사
107  81  user_81  38.0  50421.0    NaN         영업
108  11  user_11  28.0  64250.0  70.04         인사
109   1   user_1  56.0  59545.0  17.50        마케팅
110  19  user_19  41.0  38304.0  66.90         인사
111  31  user_31  59.0  74344.0  49.39         인사

In [4]:
df.drop_duplicates(keep=False)

     id      name   age   salary  score department
1     2    user_2  46.0  36399.0  98.22         영업
2     3    user_3  32.0  57141.0  51.66         개발
3     4    user_4  60.0  69555.0  26.08         재무
4     5    user_5  25.0  53174.0  99.63         개발
5     6    user_6   NaN  58956.0  96.54         개발
..  ...       ...   ...      ...    ...        ...
95   96   user_96  24.0  63100.0  88.66         재무
96   97   user_97  26.0 -30000.0   2.76        마케팅
97   98   user_98  41.0  28348.0  57.89        마케팅
98   99   user_99  18.0  34584.0  43.85         재무
99  100  user_100  61.0  61119.0  67.20         인사

[88 rows x 6 columns]